### ISSUE TITLE
print styles

### ISSUE THREAD

**Issue by TimPietrusky** [synoa/bullgrid#1]
Create an optional namespace for print:

```
.print-one-half
.print-one-whole
...
```

**Comment by kevingimbel** [comment]
This can be done by using the following grid setup.

```sass
@media print {
  grid-setup("print-");
}
```
This way the `print-` classes will be used instead of the viewport based once. I'll include it in the README.md as a comment and as a comment inside the code, but this should not be "standard" IMO.
